development:
  adapter: postgresql
  encoding: unicode
  database: mycellar_development
  pool: 5
  username: vswamy
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: mycellar_test
  pool: 5
  username: vswamy
  password: 