# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856f13edfd2a337948bd4a770f4191b0f72c1188c5b474fea5a7706f7bb63deb93bab5bdac8996063596e77257417a549ebdbd8ef2a38953d299bd3ab1e83f63

test:
  secret_key_base: 4c4f77635a0ea13aefbba140b17b1754b15e4538f7b2ecb47b943b9982eb406391cd10dbd271ab22d84cc7f71b268a911fb644f64e5a6bc6eae1599700635ce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
